### PR TITLE
#3 Use is_sidebar_visible and set_sidebar_visible instead of guessing

### PR DESCRIPTION
**Pull request by ktaragorn**
Remove now unnecessary code for visibility tracking

The behavior when in quick panels is also fixed

### CODE REVIEW

**Comment by mfkaptan** [comment]
Just wanted to say nice job, these changes solved my issues! I hope it gets merged asap.

**Comment by ktaragorn** [comment]
@mfkaptan Thanks for testing, I hope so too!

**Comment by aristidesfl** [comment]
ping

**Comment by karthikbeam** [comment]
@xunker can I get a review on this?

**Comment by ktaragorn** [comment]
@xunker  Awesome! Please let us know once published so I can use that instead of my branch

**Pull request merged**
